---
kind: workerService
version: udx.io/worker-v1/service
services:
  # Initial setup service
  - name: "k8s-setup"
    autostart: true
    autorestart: false
    command: "/opt/sources/rabbitci/rabbit-ssh/bin/setup-kubernetes.sh"

  # Main SSH server service
  - name: "rabbit-ssh-server"
    autostart: true
    autorestart: true
    command: "node bin/server.js"
    envs:
      - "NODE_ENV=production"

  # SSHD daemon
  - name: "sshd"
    autostart: true
    autorestart: true
    command: "/usr/sbin/sshd -D"
    envs:
      - "SSHD_PORT=22"

  # Firebase deployment watcher
  - name: "firebase-consume"
    autostart: true
    autorestart: false
    command: "node bin/firebase.consume.js"
    envs:
      - "NODE_ENV=production"