---
kind: workerService
version: udx.io/worker-v1/service
services:
  - name: "k8s-setup"
    autostart: true
    autorestart: false
    command: "/opt/sources/rabbitci/rabbit-ssh/bin/setup-kubernetes.sh"

  - name: "rabbit-ssh-server"
    autostart: true
    autorestart: true
    command: "node bin/server.js"
    envs:
      - "NODE_ENV=production"

  - name: "sshd"
    autostart: true
    autorestart: true
    command: "/usr/sbin/sshd -D"
    envs:
      - "SSHD_PORT=22"